# Generated by Django 3.1.5 on 2021-01-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210118_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created',), 'verbose_name': '회원들', 'verbose_name_plural': '회원리스트'},
        ),
    ]
