# Generated by Django 3.1.5 on 2021-01-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descriptsion',
            new_name='description',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categoris',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y-%m-%d')),
                ('desription', models.TextField(blank=True)),
                ('meta_desription', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('available_display', models.BooleanField(default=True, verbose_name='Display')),
                ('available_order', models.BooleanField(default=True, verbose_name='Order')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '판매중인 상품들',
                'db_table': 'products',
                'ordering': ('-created',),
            },
        ),
    ]
