# Generated by Django 3.1.5 on 2021-01-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210118_2230'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together={('id', 'slug')},
        ),
    ]
