# Generated by Django 3.1.5 on 2021-01-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210118_2231'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together=set(),
        ),
    ]
