# Generated by Django 3.1.5 on 2021-01-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210118_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meta_desription',
            new_name='meta_description',
        ),
    ]
